$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1389330947081.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"denglu1",
"denglu2",
"kong",
"jiaodu1",
"jiaodu2",
"x1",
"y1",
"x2",
"y2",
"f1",
"f2"],
  "defaultBackgroundImageInfo":{
    "path":"images/主页/bg.jpg",
    "width":640,
    "height":1136},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"7f85bb35caba44f292200d7792d0f61c",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"设置 值于 kong = &quot;&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetGlobalVariableValue",
                      "arguments":[{
                          "exprType":"globalVariableLiteral",
                          "variableName":"kong"},
{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"db79c171649f4fcb98c0f5ccfbbae17a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":70,
              "y":118},
            "size":{
              "width":501,
              "height":901},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":25,
              "color":{
                "r":255,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcba0a7272ed49b7aedc9be34a1dabea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":70,
                  "y":118},
                "size":{
                  "width":501,
                  "height":901},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":25,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"773c520386074af49a1d49ef98ddf476",
          "label":"dk",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":220,
              "y":700},
            "size":{
              "width":201,
              "height":71},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":25,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"101b74c4802a4e1a9ed1971d57e0f899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":700},
                "size":{
                  "width":201,
                  "height":71},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":25,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 页面 1",
                      "target":{
                        "targetType":"page",
                        "url":"页面_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/dk_u2.png"}},
{
          "id":"fe740eb2115e4d5c83eacb7a383afacc",
          "label":"yhm",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":170,
              "y":560},
            "size":{
              "width":300,
              "height":37}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 yhm = 值于 kong",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["fe740eb2115e4d5c83eacb7a383afacc"]},
{
                                "exprType":"fcall",
                                "functionName":"GetGlobalVariableValue",
                                "arguments":[{
                                    "exprType":"globalVariableLiteral",
                                    "variableName":"kong"}]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 yhm ≠ &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"!=",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["fe740eb2115e4d5c83eacb7a383afacc"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 denglu1 = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"denglu1"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 值于 kong = 文字于 yhm",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"kong"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["fe740eb2115e4d5c83eacb7a383afacc"]}]}]}]}}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 This = &quot;用户名&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"用户名                                       ",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 值于 denglu1 = &quot;0&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"denglu1"},
{
                                "exprType":"stringLiteral",
                                "value":"0",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 值于 kong = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"kong"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 2<br> (If 值于 denglu1 ≠ &quot;1&quot; 或 值于 denglu2 ≠ &quot;1&quot;)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu1"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu2"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"enableDisableWidgets",
                      "description":"禁用 dk",
                      "pathToInfo":[{
                          "objectPath":["773c520386074af49a1d49ef98ddf476"],
                          "enableDisableInfo":{
                            "enable":false}}]}]},
{
                  "description":"用例 1<br> (If 值于 denglu1 = &quot;1&quot; 和 值于 denglu2 = &quot;1&quot;)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu1"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu2"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"启用 dk",
                      "pathToInfo":[{
                          "objectPath":["773c520386074af49a1d49ef98ddf476"],
                          "enableDisableInfo":{
                            "enable":true}}]}]}]}},
          "tabbable":true},
{
          "id":"8c423096a3fc4db69c6edb1bf1548c2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":220,
              "y":791},
            "size":{
              "width":201,
              "height":71},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":25,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb4dc2e9c14548bab6c9d88734498712",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":791},
                "size":{
                  "width":201,
                  "height":71},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":25,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u5.png"}},
{
          "id":"1c4365371ffa43f88dcac0bd4990197e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":597},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u7_line.png"}},
{
          "id":"0370b658ec1e4dea8103148efd86dbc9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":654},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u7_line.png"}},
{
          "id":"3fa5d74e3aad4701878557fcb5d13ed4",
          "label":"mm2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":172,
              "y":624},
            "size":{
              "width":297,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c46997c55fc4f249a95bb44a7355c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":172,
                  "y":624},
                "size":{
                  "width":297,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e840a7edbde94f23835eac7b9a292e3c",
          "label":"mm",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":170,
              "y":617},
            "size":{
              "width":300,
              "height":37}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 mm2 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4c46997c55fc4f249a95bb44a7355c05"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 This ≠ &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"!=",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 denglu2 = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"denglu2"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 denglu2 = &quot;0&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"denglu2"},
{
                                "exprType":"stringLiteral",
                                "value":"0",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"设置 文字于 mm2 = &quot;密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4c46997c55fc4f249a95bb44a7355c05"]},
{
                                "exprType":"stringLiteral",
                                "value":"密码",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]},
{
                  "description":"用例 2<br> (If 值于 denglu1 ≠ &quot;1&quot; 或 值于 denglu2 ≠ &quot;1&quot;)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu1"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu2"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"禁用 dk",
                      "pathToInfo":[{
                          "objectPath":["773c520386074af49a1d49ef98ddf476"],
                          "enableDisableInfo":{
                            "enable":false}}]}]},
{
                  "description":"用例 1<br> (If 值于 denglu1 = &quot;1&quot; 和 值于 denglu2 = &quot;1&quot;)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu1"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"denglu2"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"启用 dk",
                      "pathToInfo":[{
                          "objectPath":["773c520386074af49a1d49ef98ddf476"],
                          "enableDisableInfo":{
                            "enable":true}}]}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "db79c171649f4fcb98c0f5ccfbbae17a":{
      "scriptId":"u0"},
    "fcba0a7272ed49b7aedc9be34a1dabea":{
      "scriptId":"u1"},
    "773c520386074af49a1d49ef98ddf476":{
      "scriptId":"u2"},
    "101b74c4802a4e1a9ed1971d57e0f899":{
      "scriptId":"u3"},
    "fe740eb2115e4d5c83eacb7a383afacc":{
      "scriptId":"u4"},
    "8c423096a3fc4db69c6edb1bf1548c2f":{
      "scriptId":"u5"},
    "eb4dc2e9c14548bab6c9d88734498712":{
      "scriptId":"u6"},
    "1c4365371ffa43f88dcac0bd4990197e":{
      "scriptId":"u7"},
    "0370b658ec1e4dea8103148efd86dbc9":{
      "scriptId":"u8"},
    "3fa5d74e3aad4701878557fcb5d13ed4":{
      "scriptId":"u9"},
    "4c46997c55fc4f249a95bb44a7355c05":{
      "scriptId":"u10"},
    "e840a7edbde94f23835eac7b9a292e3c":{
      "scriptId":"u11"}}});