$axure.loadCurrentPage({
  "url":"页面_6.html",
  "generationDate":new Date(1389334355036.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"kong",
"denglu1",
"denglu2",
"kong2",
"zc1",
"zc2",
"zc3",
"kong3",
"yi",
"jiache"],
  "page":{
    "packageId":"0c3c52b1c8cf4525923efa7679fa3c08",
    "type":"Axure:Page",
    "name":"页面 6",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"方正细等线_GBK",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setPanelState",
                "description":"设置 (动态面板) to 状态1 向右滑动 in 500ms",
                "panelsToStates":[{
                    "panelPath":["6d68a3ee48674558bca4247e0d8539cf"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "animateIn":{
                          "easing":"slideRight",
                          "duration":500},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"6d68a3ee48674558bca4247e0d8539cf",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"322eabb528d24c378a85a95e09a78484",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"0863a47b8a7a4c49bf1ecec5b13741b3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"90735bbc1eea4659bbef45edc54b7aae",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":36,
                      "y":44},
                    "size":{
                      "width":24,
                      "height":46}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5eb3ecbd9c54f92857351425a64f127",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":36,
                          "y":44},
                        "size":{
                          "width":24,
                          "height":46}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 值于 jiache = &quot;1&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetGlobalVariableValue",
                                    "arguments":[{
                                        "exprType":"globalVariableLiteral",
                                        "variableName":"jiache"},
{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]}]}]}},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 页面 3",
                              "target":{
                                "targetType":"page",
                                "url":"页面_3.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/页面_1/u2.png"}},
{
                  "id":"9e0b18b4123f47c3880e1b520fe4bdc6",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontSize":"40px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":268,
                      "y":44},
                    "size":{
                      "width":102,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c9c30b5c65044105b99a8dbc7e0a64c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontSize":"40px",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":268,
                          "y":44},
                        "size":{
                          "width":102,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c90b3f7c428548d3b5a96025a5974211",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":30,
                      "y":140},
                    "size":{
                      "width":580,
                      "height":170},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"9",
                    "outerShadow":{
                      "on":true,
                      "offsetX":1,
                      "offsetY":1,
                      "blurRadius":10,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c497bc0123844218088158fe65cc606",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":30,
                          "y":140},
                        "size":{
                          "width":580,
                          "height":170},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"9",
                        "outerShadow":{
                          "on":true,
                          "offsetX":1,
                          "offsetY":1,
                          "blurRadius":10,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u5.png"}},
{
                  "id":"e82f8ff5ac974200bd4ad43c92a01e02",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":75,
                      "y":172},
                    "size":{
                      "width":133,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03e8cabf65634f8a82677c58cb42dd96",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":75,
                          "y":172},
                        "size":{
                          "width":133,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f7f284bddb4948ffa64ddd6e0a7c0a95",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":75,
                      "y":249},
                    "size":{
                      "width":133,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33dcc24c3c694ec980cc431dd1fe6573",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":75,
                          "y":249},
                        "size":{
                          "width":133,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f386405d4d2d4434b815e4c65cb4822e",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":42,
                      "y":219},
                    "size":{
                      "width":556,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_6/u11_line.png"}},
{
                  "id":"7dd3b83bf9b64f45904b2a377b069f48",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":498,
                      "y":155},
                    "size":{
                      "width":100,
                      "height":69},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2865b48d7bd5421f8dfe606feae7c45f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":498,
                          "y":155},
                        "size":{
                          "width":100,
                          "height":69},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u12.png"}},
{
                  "id":"b84a7494f67045438b63f8918bc348c4",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":498,
                      "y":229},
                    "size":{
                      "width":100,
                      "height":69},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"059d39786c714ea89f6fc88bf411e907",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":498,
                          "y":229},
                        "size":{
                          "width":100,
                          "height":69},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u12.png"}},
{
                  "id":"8baeb87de9a04abc92e04ea008a5892a",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":30,
                      "y":370},
                    "size":{
                      "width":580,
                      "height":250},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"9",
                    "outerShadow":{
                      "on":true,
                      "offsetX":1,
                      "offsetY":1,
                      "blurRadius":10,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a83770b4503449f798ab798f82f0757a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":30,
                          "y":370},
                        "size":{
                          "width":580,
                          "height":250},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"9",
                        "outerShadow":{
                          "on":true,
                          "offsetX":1,
                          "offsetY":1,
                          "blurRadius":10,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u16.png"}},
{
                  "id":"9a6aef47bc5044e68f28d19bc0642e64",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":75,
                      "y":402},
                    "size":{
                      "width":362,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f50a21c48794c5a917c49202275516b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":75,
                          "y":402},
                        "size":{
                          "width":362,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"812a964da468432ea7a805072e8cea58",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":75,
                      "y":479},
                    "size":{
                      "width":133,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99e0f3e618ed47358c6925e59a5d615d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":75,
                          "y":479},
                        "size":{
                          "width":133,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"739ca9b85002473aa8c30b258a89fb4a",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":42,
                      "y":449},
                    "size":{
                      "width":556,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_6/u11_line.png"}},
{
                  "id":"5f298bfab43e468c9a58b99a64daf40e",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":498,
                      "y":385},
                    "size":{
                      "width":100,
                      "height":69},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c80ed542166a4077ab0300f144db1713",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":498,
                          "y":385},
                        "size":{
                          "width":100,
                          "height":69},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u12.png"}},
{
                  "id":"2085460b81384ea5a68e50eba51d15a2",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":498,
                      "y":459},
                    "size":{
                      "width":100,
                      "height":69},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00d138af05364792b10dc5566af79f6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":498,
                          "y":459},
                        "size":{
                          "width":100,
                          "height":69},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u12.png"}},
{
                  "id":"a47a938d43db4f0a88af905fe2a9e22e",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":75,
                      "y":554},
                    "size":{
                      "width":133,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4872c2f1a8e493bbacffa9f49b1e208",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":75,
                          "y":554},
                        "size":{
                          "width":133,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"11472cc33b32422ab6143aa6af80fcc0",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":42,
                      "y":527},
                    "size":{
                      "width":556,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_6/u11_line.png"}},
{
                  "id":"b16409528b734e4cb9727576924eb4a6",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":498,
                      "y":534},
                    "size":{
                      "width":100,
                      "height":69},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f342673c78ca45daa9d9535beeb4e5ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":498,
                          "y":534},
                        "size":{
                          "width":100,
                          "height":69},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u12.png"}},
{
                  "id":"f1a1548c53104e449660f5b03f4248a2",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":30,
                      "y":680},
                    "size":{
                      "width":580,
                      "height":170},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"9",
                    "outerShadow":{
                      "on":true,
                      "offsetX":1,
                      "offsetY":1,
                      "blurRadius":10,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a617fe40acc24b26b5b718f80c74a03d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":30,
                          "y":680},
                        "size":{
                          "width":580,
                          "height":170},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"9",
                        "outerShadow":{
                          "on":true,
                          "offsetX":1,
                          "offsetY":1,
                          "blurRadius":10,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u5.png"}},
{
                  "id":"0f2ed12e65864e30898ebffa971f5e58",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":75,
                      "y":712},
                    "size":{
                      "width":199,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab55506739d84d5caa65e59235613311",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":75,
                          "y":712},
                        "size":{
                          "width":199,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06536a606fb84618a291a2117f84ad67",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":75,
                      "y":789},
                    "size":{
                      "width":67,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5fc476258a340c498acb013a36faae9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":75,
                          "y":789},
                        "size":{
                          "width":67,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5633d1ce32f24a8c8d3e3c95dde48730",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":42,
                      "y":759},
                    "size":{
                      "width":556,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_6/u11_line.png"}},
{
                  "id":"57b474abc5ac4ef0aced58ec1a819987",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":498,
                      "y":695},
                    "size":{
                      "width":100,
                      "height":69},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe68b976308f4053958f5cc7a1528bc3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":498,
                          "y":695},
                        "size":{
                          "width":100,
                          "height":69},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u12.png"}},
{
                  "id":"e3a2f16b87594e06ac727f62ba16a86c",
                  "label":"",
                  "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":498,
                      "y":769},
                    "size":{
                      "width":100,
                      "height":69},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76811e1eeffb422caeb0d15248c75895",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d68a3ee48674558bca4247e0d8539cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正细等线_GBK Regular', '方正细等线_GBK'",
                        "fontWeight":"400",
                        "fontStyle":"normal",
                        "location":{
                          "x":498,
                          "y":769},
                        "size":{
                          "width":100,
                          "height":69},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_6/u12.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "6d68a3ee48674558bca4247e0d8539cf":{
      "scriptId":"u0"},
    "90735bbc1eea4659bbef45edc54b7aae":{
      "scriptId":"u1"},
    "a5eb3ecbd9c54f92857351425a64f127":{
      "scriptId":"u2"},
    "9e0b18b4123f47c3880e1b520fe4bdc6":{
      "scriptId":"u3"},
    "c9c30b5c65044105b99a8dbc7e0a64c4":{
      "scriptId":"u4"},
    "c90b3f7c428548d3b5a96025a5974211":{
      "scriptId":"u5"},
    "8c497bc0123844218088158fe65cc606":{
      "scriptId":"u6"},
    "e82f8ff5ac974200bd4ad43c92a01e02":{
      "scriptId":"u7"},
    "03e8cabf65634f8a82677c58cb42dd96":{
      "scriptId":"u8"},
    "f7f284bddb4948ffa64ddd6e0a7c0a95":{
      "scriptId":"u9"},
    "33dcc24c3c694ec980cc431dd1fe6573":{
      "scriptId":"u10"},
    "f386405d4d2d4434b815e4c65cb4822e":{
      "scriptId":"u11"},
    "7dd3b83bf9b64f45904b2a377b069f48":{
      "scriptId":"u12"},
    "2865b48d7bd5421f8dfe606feae7c45f":{
      "scriptId":"u13"},
    "b84a7494f67045438b63f8918bc348c4":{
      "scriptId":"u14"},
    "059d39786c714ea89f6fc88bf411e907":{
      "scriptId":"u15"},
    "8baeb87de9a04abc92e04ea008a5892a":{
      "scriptId":"u16"},
    "a83770b4503449f798ab798f82f0757a":{
      "scriptId":"u17"},
    "9a6aef47bc5044e68f28d19bc0642e64":{
      "scriptId":"u18"},
    "1f50a21c48794c5a917c49202275516b":{
      "scriptId":"u19"},
    "812a964da468432ea7a805072e8cea58":{
      "scriptId":"u20"},
    "99e0f3e618ed47358c6925e59a5d615d":{
      "scriptId":"u21"},
    "739ca9b85002473aa8c30b258a89fb4a":{
      "scriptId":"u22"},
    "5f298bfab43e468c9a58b99a64daf40e":{
      "scriptId":"u23"},
    "c80ed542166a4077ab0300f144db1713":{
      "scriptId":"u24"},
    "2085460b81384ea5a68e50eba51d15a2":{
      "scriptId":"u25"},
    "00d138af05364792b10dc5566af79f6b":{
      "scriptId":"u26"},
    "a47a938d43db4f0a88af905fe2a9e22e":{
      "scriptId":"u27"},
    "c4872c2f1a8e493bbacffa9f49b1e208":{
      "scriptId":"u28"},
    "11472cc33b32422ab6143aa6af80fcc0":{
      "scriptId":"u29"},
    "b16409528b734e4cb9727576924eb4a6":{
      "scriptId":"u30"},
    "f342673c78ca45daa9d9535beeb4e5ec":{
      "scriptId":"u31"},
    "f1a1548c53104e449660f5b03f4248a2":{
      "scriptId":"u32"},
    "a617fe40acc24b26b5b718f80c74a03d":{
      "scriptId":"u33"},
    "0f2ed12e65864e30898ebffa971f5e58":{
      "scriptId":"u34"},
    "ab55506739d84d5caa65e59235613311":{
      "scriptId":"u35"},
    "06536a606fb84618a291a2117f84ad67":{
      "scriptId":"u36"},
    "b5fc476258a340c498acb013a36faae9":{
      "scriptId":"u37"},
    "5633d1ce32f24a8c8d3e3c95dde48730":{
      "scriptId":"u38"},
    "57b474abc5ac4ef0aced58ec1a819987":{
      "scriptId":"u39"},
    "fe68b976308f4053958f5cc7a1528bc3":{
      "scriptId":"u40"},
    "e3a2f16b87594e06ac727f62ba16a86c":{
      "scriptId":"u41"},
    "76811e1eeffb422caeb0d15248c75895":{
      "scriptId":"u42"}}});