$axure.loadCurrentPage({
  "url":"页面_8.html",
  "generationDate":new Date(1389334355366.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"kong",
"denglu1",
"denglu2",
"kong2",
"zc1",
"zc2",
"zc3",
"kong3",
"yi",
"jiache"],
  "page":{
    "packageId":"e5cd96b9743e4356a20d125771b18965",
    "type":"Axure:Page",
    "name":"页面 8",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"892cedbe3f8e47c493f68f5d74877323",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4680748399c642599defea6af8ee580f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_8/u0.gif"}},
{
          "id":"a6973c5a192f477eae1f9bd2c2596f3f",
          "label":"hui",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "opacity":"1"}},
            "opacity":"0",
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":105,
              "y":216},
            "size":{
              "width":430,
              "height":430},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"50",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d017f81f6bb4ef29c62e521b8c5fd67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "opacity":"1"}},
                "opacity":"0",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":105,
                  "y":216},
                "size":{
                  "width":430,
                  "height":430},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"50",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"images/页面_8/hui_u2_selected.png"}},
{
          "id":"2798f099bddf431fa553e3dbf1d5efbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":216},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"554d3a4bc5994b76ab4dd5ca2ec66b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":216},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 hui = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a6973c5a192f477eae1f9bd2c2596f3f"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/页面_8/u4.png"}},
{
          "id":"e6ccd55fbed247d586e3349fc4d628a1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 页面 3",
                      "target":{
                        "targetType":"page",
                        "url":"页面_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6d6b15c4e2974536a0a6551f023596ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":668},
            "size":{
              "width":405,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2dc5f2824e485abae0701111be794c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":668},
                "size":{
                  "width":405,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面_8/u7.png"}},
{
          "id":"6dc23ba68b0d47a38d6c28010aae5fe6",
          "label":"1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":277.5,
              "y":714},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 z2 x 轴拖动,<br>z1 x 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["5bdf30b94b1b4f1e887d4efa1e8c9652"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["625accca8a8e4b97bbcc882c2cb336ce"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If &quot;[[LVAR1.x]]&quot; &lt; &quot;-42&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[LVAR1.x]]",
                      "localVariables":{
                        "lvar1":{
                          "exprType":"fcall",
                          "functionName":"GetWidget",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["625accca8a8e4b97bbcc882c2cb336ce"]}]}},
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"lvar1"},
                          "prop":"x"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"-42",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 z1 到 (-92,8) 线性 500ms,<br>z2 到 (8,8) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["625accca8a8e4b97bbcc882c2cb336ce"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"-92",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}},
{
                          "objectPath":["5bdf30b94b1b4f1e887d4efa1e8c9652"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 z1 到 (8,8) 线性 500ms,<br>z2 到 (108,8) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["625accca8a8e4b97bbcc882c2cb336ce"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}},
{
                          "objectPath":["5bdf30b94b1b4f1e887d4efa1e8c9652"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"108",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"49641e13690b4375a44c39ed164c29d7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"625accca8a8e4b97bbcc882c2cb336ce",
                  "label":"z1",
                  "parentDynamicPanel":"6dc23ba68b0d47a38d6c28010aae5fe6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-42,
                      "y":8},
                    "size":{
                      "width":84,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"481a25fe5fbd4aba80757904b82f50b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6dc23ba68b0d47a38d6c28010aae5fe6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-42,
                          "y":8},
                        "size":{
                          "width":84,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_3/q2_u51.png"}},
{
                  "id":"5bdf30b94b1b4f1e887d4efa1e8c9652",
                  "label":"z2",
                  "parentDynamicPanel":"6dc23ba68b0d47a38d6c28010aae5fe6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":58,
                      "y":8},
                    "size":{
                      "width":84,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cea309b738914e92a0d9c948ad66ce1d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6dc23ba68b0d47a38d6c28010aae5fe6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":58,
                          "y":8},
                        "size":{
                          "width":84,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_3/q1_u49.png"}}]}]},
{
          "id":"d92ac2c82c0b4b30b4fa7f758caa4434",
          "label":"2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":277.5,
              "y":824},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 z3 x 轴拖动,<br>z4 x 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["d0b20c3630a149afa778e625ee4a0fae"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["2075ce40b17c4503be5444ebb870cbf6"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If &quot;[[LVAR1.x]]&quot; &lt; &quot;-42&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[LVAR1.x]]",
                      "localVariables":{
                        "lvar1":{
                          "exprType":"fcall",
                          "functionName":"GetWidget",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["d0b20c3630a149afa778e625ee4a0fae"]}]}},
                      "stos":[{
                          "computedType":"int",
                          "sto":"propCall",
                          "thisSTO":{
                            "sto":"var",
                            "name":"lvar1"},
                          "prop":"x"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"-42",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 z3 到 (-92,8) 线性 500ms,<br>z4 到 (8,8) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["d0b20c3630a149afa778e625ee4a0fae"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"-92",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}},
{
                          "objectPath":["2075ce40b17c4503be5444ebb870cbf6"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 z3 到 (8,8) 线性 500ms,<br>z4 到 (108,8) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["d0b20c3630a149afa778e625ee4a0fae"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}},
{
                          "objectPath":["2075ce40b17c4503be5444ebb870cbf6"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"108",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"8",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c29260b275c8466eb005640cf9fbc4a7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d0b20c3630a149afa778e625ee4a0fae",
                  "label":"z3",
                  "parentDynamicPanel":"d92ac2c82c0b4b30b4fa7f758caa4434",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-42,
                      "y":8},
                    "size":{
                      "width":82,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30eb6536b48345c58412f08154596a7f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d92ac2c82c0b4b30b4fa7f758caa4434",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-42,
                          "y":8},
                        "size":{
                          "width":82,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_3/q3_u53.png"}},
{
                  "id":"2075ce40b17c4503be5444ebb870cbf6",
                  "label":"z4",
                  "parentDynamicPanel":"d92ac2c82c0b4b30b4fa7f758caa4434",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":58,
                      "y":8},
                    "size":{
                      "width":83,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"adf08be4d3754e87948bfe69833d1aee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d92ac2c82c0b4b30b4fa7f758caa4434",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":58,
                          "y":8},
                        "size":{
                          "width":83,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_3/q4_u55.png"}}]}]},
{
          "id":"c038f50bb26149f8a21bab32d7c0c9c7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":960},
            "size":{
              "width":280,
              "height":90}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 页面 9",
                      "target":{
                        "targetType":"page",
                        "url":"页面_9.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "892cedbe3f8e47c493f68f5d74877323":{
      "scriptId":"u0"},
    "4680748399c642599defea6af8ee580f":{
      "scriptId":"u1"},
    "a6973c5a192f477eae1f9bd2c2596f3f":{
      "scriptId":"u2"},
    "0d017f81f6bb4ef29c62e521b8c5fd67":{
      "scriptId":"u3"},
    "2798f099bddf431fa553e3dbf1d5efbd":{
      "scriptId":"u4"},
    "554d3a4bc5994b76ab4dd5ca2ec66b1c":{
      "scriptId":"u5"},
    "e6ccd55fbed247d586e3349fc4d628a1":{
      "scriptId":"u6"},
    "6d6b15c4e2974536a0a6551f023596ee":{
      "scriptId":"u7"},
    "5c2dc5f2824e485abae0701111be794c":{
      "scriptId":"u8"},
    "6dc23ba68b0d47a38d6c28010aae5fe6":{
      "scriptId":"u9"},
    "625accca8a8e4b97bbcc882c2cb336ce":{
      "scriptId":"u10"},
    "481a25fe5fbd4aba80757904b82f50b5":{
      "scriptId":"u11"},
    "5bdf30b94b1b4f1e887d4efa1e8c9652":{
      "scriptId":"u12"},
    "cea309b738914e92a0d9c948ad66ce1d":{
      "scriptId":"u13"},
    "d92ac2c82c0b4b30b4fa7f758caa4434":{
      "scriptId":"u14"},
    "d0b20c3630a149afa778e625ee4a0fae":{
      "scriptId":"u15"},
    "30eb6536b48345c58412f08154596a7f":{
      "scriptId":"u16"},
    "2075ce40b17c4503be5444ebb870cbf6":{
      "scriptId":"u17"},
    "adf08be4d3754e87948bfe69833d1aee":{
      "scriptId":"u18"},
    "c038f50bb26149f8a21bab32d7c0c9c7":{
      "scriptId":"u19"}}});