$axure.loadCurrentPage({
  "url":"page_2.html",
  "generationDate":new Date(1402071733080.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"kaiguan1",
"kaiguan2",
"hua"],
  "page":{
    "packageId":"934659fbf5d24f20930afa0e8ad1ea42",
    "type":"Axure:Page",
    "name":"Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});