$axure.loadCurrentPage({
  "url":"页面_4.html",
  "generationDate":new Date(1389334354787.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"kong",
"denglu1",
"denglu2",
"kong2",
"zc1",
"zc2",
"zc3",
"kong3",
"yi",
"jiache"],
  "page":{
    "packageId":"4b2da8733b32469c8b6f43fc84aea23a",
    "type":"Axure:Page",
    "name":"页面 4",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setPanelState",
                "description":"设置 (动态面板) to State1 向右滑动 in 1000ms",
                "panelsToStates":[{
                    "panelPath":["ca772ce29c31459982b8e1c5a39e0d1a"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "animateIn":{
                          "easing":"slideRight",
                          "duration":1000},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"ca772ce29c31459982b8e1c5a39e0d1a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"dfe8fc45efaf42f0a47d663fbff43df8",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"1738b164377d491e93c3c45afb70f7e2",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cb5d4de682c046d7a5948d26d3a95187",
                  "label":"",
                  "parentDynamicPanel":"ca772ce29c31459982b8e1c5a39e0d1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":1136}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ece9460e28d4e4c8718868c751f2bd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca772ce29c31459982b8e1c5a39e0d1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":1136}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_4/u1.jpg"}},
{
                  "id":"41373e22b0a6415b8dfddf6952b9afdf",
                  "label":"",
                  "parentDynamicPanel":"ca772ce29c31459982b8e1c5a39e0d1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":1041},
                    "size":{
                      "width":640,
                      "height":95}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da216b1c86bc4b9ea400f136630a3b7e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca772ce29c31459982b8e1c5a39e0d1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":1041},
                        "size":{
                          "width":640,
                          "height":95}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_3/u37.png"}},
{
                  "id":"d8b4b2cce6374a8f9ebcb755fd884b8f",
                  "label":"",
                  "parentDynamicPanel":"ca772ce29c31459982b8e1c5a39e0d1a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":1050},
                    "size":{
                      "width":90,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 页面 3",
                              "target":{
                                "targetType":"page",
                                "url":"页面_3.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"c46dc8dc3449420ab0ab4a27a1b4e2b4",
                  "label":"",
                  "parentDynamicPanel":"ca772ce29c31459982b8e1c5a39e0d1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":184,
                      "y":1000},
                    "size":{
                      "width":272,
                      "height":92},
                    "outerShadow":{
                      "on":true,
                      "offsetX":2,
                      "offsetY":2,
                      "blurRadius":15,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0a54b9cc10f498b9c549fcfae5146bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ca772ce29c31459982b8e1c5a39e0d1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":184,
                          "y":1000},
                        "size":{
                          "width":272,
                          "height":92},
                        "outerShadow":{
                          "on":true,
                          "offsetX":2,
                          "offsetY":2,
                          "blurRadius":15,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 页面 5",
                              "target":{
                                "targetType":"page",
                                "url":"页面_5.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/页面_4/u6.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "ca772ce29c31459982b8e1c5a39e0d1a":{
      "scriptId":"u0"},
    "cb5d4de682c046d7a5948d26d3a95187":{
      "scriptId":"u1"},
    "3ece9460e28d4e4c8718868c751f2bd3":{
      "scriptId":"u2"},
    "41373e22b0a6415b8dfddf6952b9afdf":{
      "scriptId":"u3"},
    "da216b1c86bc4b9ea400f136630a3b7e":{
      "scriptId":"u4"},
    "d8b4b2cce6374a8f9ebcb755fd884b8f":{
      "scriptId":"u5"},
    "c46dc8dc3449420ab0ab4a27a1b4e2b4":{
      "scriptId":"u6"},
    "e0a54b9cc10f498b9c549fcfae5146bb":{
      "scriptId":"u7"}}});