$axure.loadCurrentPage({
  "url":"页面_2.html",
  "generationDate":new Date(1389330947927.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"denglu1",
"denglu2",
"kong",
"jiaodu1",
"jiaodu2",
"x1",
"y1",
"x2",
"y2",
"f1",
"f2"],
  "defaultBackgroundImageInfo":{
    "path":"images/主页/bg.jpg",
    "width":640,
    "height":1136},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"48175ee70faa4201a595311e1adbce9b",
    "type":"Axure:Page",
    "name":"页面 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setPanelState",
                "description":"设置 (动态面板) to State1 向右滑动 in 500ms",
                "panelsToStates":[{
                    "panelPath":["b33baae50e56473a89a01bdd62c0080a"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "animateIn":{
                          "easing":"slideRight",
                          "duration":500},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"b33baae50e56473a89a01bdd62c0080a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":40},
            "size":{
              "width":594,
              "height":1046}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d920ed3733624826be848c4bccb132e9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"560e26847543430fa9228bf503725fc0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"da1484641abb4ad0abaa03daf186f3f1",
                  "label":"",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":594,
                      "height":1046}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e98fe0c636841d590d5b1da51b78323",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":594,
                          "height":1046}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_1/u1.png"}},
{
                  "id":"34685f437bb949abbff1217f47286a37",
                  "label":"zhe",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":70,
                      "y":878},
                    "size":{
                      "width":454,
                      "height":75},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c4ee13a5661418780ebafd9a3bf60e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":70,
                          "y":878},
                        "size":{
                          "width":454,
                          "height":75},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_2/zhe_u3.png"}},
{
                  "id":"733c7d418bf74984b079d9c434efe369",
                  "label":"diban",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":616},
                    "size":{
                      "width":454,
                      "height":340}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"bed56c491f0849d8a4fcaa20e3cbf5ef",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[]}]},
{
                  "id":"d731c00f63ce470facd4ded43b6e87fa",
                  "label":"",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":626},
                    "size":{
                      "width":454,
                      "height":312}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a99e97b7a8de476abb7607a1894c6101",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":70,
                          "y":626},
                        "size":{
                          "width":454,
                          "height":312}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_2/u6.png"}},
{
                  "id":"179d3cd6031a4c66a51b271abde3fbef",
                  "label":"xx",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":594,
                      "height":516}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"bb773db83a9340c089a737048cf37225",
                      "label":"logo",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"18ca3b3e2cac45e5920c2702db6c679d",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":30,
                              "y":80},
                            "size":{
                              "width":266,
                              "height":266}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"33ca4150375144d193edeac5d7621bcd",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":30,
                                  "y":80},
                                "size":{
                                  "width":266,
                                  "height":266}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u9.png"}},
{
                          "id":"c2cf086899c148f892f0c10b3f8b58a9",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":33,
                              "y":80},
                            "size":{
                              "width":267,
                              "height":265}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"20045bee4d84498aab1c50946fd500b1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":33,
                                  "y":80},
                                "size":{
                                  "width":267,
                                  "height":265}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u11.png"}},
{
                          "id":"434bbec138ca44ed831f356a517d9871",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "fontName":"'Segoe Print Regular', 'Segoe Print'",
                            "fontSize":"28px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF5386B1,
                              "opacity":1},
                            "textShadow":{
                              "on":false,
                              "offsetX":1,
                              "offsetY":1,
                              "blurRadius":5,
                              "color":{
                                "r":102,
                                "g":102,
                                "b":204,
                                "a":0.647058823529412}},
                            "location":{
                              "x":335,
                              "y":220},
                            "size":{
                              "width":173,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3ef7e9f502564813b4c3523c58562632",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Segoe Print Regular', 'Segoe Print'",
                                "fontSize":"28px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF5386B1,
                                  "opacity":1},
                                "textShadow":{
                                  "on":false,
                                  "offsetX":1,
                                  "offsetY":1,
                                  "blurRadius":5,
                                  "color":{
                                    "r":102,
                                    "g":102,
                                    "b":204,
                                    "a":0.647058823529412}},
                                "location":{
                                  "x":335,
                                  "y":220},
                                "size":{
                                  "width":173,
                                  "height":50}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"4a69b97f8cb74b5eb4617cb93c7a9a91",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":true,
                          "style":{
                            "fontName":"",
                            "fontWeight":"normal",
                            "fontStyle":"normal",
                            "location":{
                              "x":445,
                              "y":270},
                            "size":{
                              "width":126,
                              "height":29}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9f28af26d9ae4a958e26cb6b6e2b0aa2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"",
                                "fontWeight":"normal",
                                "fontStyle":"normal",
                                "location":{
                                  "x":445,
                                  "y":270},
                                "size":{
                                  "width":126,
                                  "height":29}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"1cb63ceb852e42ce8f816d6d8aeb5975",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "fontSize":"18px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "stateStyles":{
                              "mouseOver":{
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":0,
                                  "offsetY":0,
                                  "blurRadius":10,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}}},
                            "location":{
                              "x":512,
                              "y":437},
                            "size":{
                              "width":54,
                              "height":53}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"566793a500b54b36be934c1009b3741c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"18px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "stateStyles":{
                                  "mouseOver":{
                                    "outerShadow":{
                                      "on":true,
                                      "offsetX":0,
                                      "offsetY":0,
                                      "blurRadius":10,
                                      "color":{
                                        "r":0,
                                        "g":0,
                                        "b":0,
                                        "a":0.349019607843137}}}},
                                "location":{
                                  "x":512,
                                  "y":437},
                                "size":{
                                  "width":54,
                                  "height":53}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u17.png",
                            "mouseOver~":"images/页面_2/u17_mouseOver.png"}}]},
{
                      "id":"aa2fac8c4c8a44278d85e6a4f05d9aac",
                      "label":"停车统计",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"45ac988c29aa4356b629ce15c034d409",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":143,
                              "y":72},
                            "size":{
                              "width":307,
                              "height":288}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5f022ce6becb4893aa4da13325273412",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":143,
                                  "y":72},
                                "size":{
                                  "width":307,
                                  "height":288}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u19.png"}},
{
                          "id":"cd35f46d743e4ee38511202a590cbfc6",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":195,
                              "y":410},
                            "size":{
                              "width":388,
                              "height":36}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"2791cf8fcde8401e8629bdbf25bc09ed",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":195,
                                  "y":410},
                                "size":{
                                  "width":388,
                                  "height":36}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"b208e363ce2549f495891bada0114b71",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "fontSize":"16px",
                            "horizontalAlignment":"left",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":185,
                              "y":460},
                            "size":{
                              "width":392,
                              "height":35},
                            "borderWidth":"-1",
                            "cornerRadiusTopLeft":"9",
                            "outerShadow":{
                              "on":true,
                              "offsetX":1,
                              "offsetY":1,
                              "blurRadius":10,
                              "color":{
                                "r":0,
                                "g":0,
                                "b":0,
                                "a":0.349019607843137}}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d35976a9270a4a88bcf7e29ad32e04be",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "fontSize":"16px",
                                "horizontalAlignment":"left",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC},
                                "location":{
                                  "x":185,
                                  "y":460},
                                "size":{
                                  "width":392,
                                  "height":35},
                                "borderWidth":"-1",
                                "cornerRadiusTopLeft":"9",
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":1,
                                  "offsetY":1,
                                  "blurRadius":10,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u23.png"}},
{
                          "id":"203b376dc69f4c289d11ca35788d42e8",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "opacity":"0.5",
                            "location":{
                              "x":382,
                              "y":462},
                            "size":{
                              "width":82,
                              "height":30},
                            "borderWidth":"-1",
                            "outerShadow":{
                              "on":true,
                              "offsetX":1,
                              "offsetY":1,
                              "blurRadius":5,
                              "color":{
                                "r":0,
                                "g":0,
                                "b":0,
                                "a":0.349019607843137}}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"39d0d6fac8a84b6fa523922cdccc0255",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000,
                                  "opacity":1},
                                "opacity":"0.5",
                                "location":{
                                  "x":382,
                                  "y":462},
                                "size":{
                                  "width":82,
                                  "height":30},
                                "borderWidth":"-1",
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":1,
                                  "offsetY":1,
                                  "blurRadius":5,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u25.png"}},
{
                          "id":"e0aee75a477d4e41bcc0619617f9a938",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "opacity":"0.5",
                            "location":{
                              "x":481.999969482422,
                              "y":462},
                            "size":{
                              "width":82,
                              "height":30},
                            "borderWidth":"-1",
                            "outerShadow":{
                              "on":true,
                              "offsetX":1,
                              "offsetY":1,
                              "blurRadius":5,
                              "color":{
                                "r":0,
                                "g":0,
                                "b":0,
                                "a":0.349019607843137}}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3cfd209d2a3744399c617bed012828f5",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000,
                                  "opacity":1},
                                "opacity":"0.5",
                                "location":{
                                  "x":481.999969482422,
                                  "y":462},
                                "size":{
                                  "width":82,
                                  "height":30},
                                "borderWidth":"-1",
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":1,
                                  "offsetY":1,
                                  "blurRadius":5,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u25.png"}},
{
                          "id":"640ad4ef83434c4d99ae88e7cba1d702",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "opacity":"0.5",
                            "location":{
                              "x":283,
                              "y":462},
                            "size":{
                              "width":82,
                              "height":30},
                            "borderWidth":"-1",
                            "outerShadow":{
                              "on":true,
                              "offsetX":1,
                              "offsetY":1,
                              "blurRadius":5,
                              "color":{
                                "r":0,
                                "g":0,
                                "b":0,
                                "a":0.349019607843137}}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f3a5bc8a67bb4837ae43a193b6e37146",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000,
                                  "opacity":1},
                                "opacity":"0.5",
                                "location":{
                                  "x":283,
                                  "y":462},
                                "size":{
                                  "width":82,
                                  "height":30},
                                "borderWidth":"-1",
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":1,
                                  "offsetY":1,
                                  "blurRadius":5,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u25.png"}}]},
{
                      "id":"e0e1a78b8e284ed9b93622957f08498c",
                      "label":"我的积分",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"bacb11d957d642478f9709412c62e0c5",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":54,
                              "y":47},
                            "size":{
                              "width":296,
                              "height":283}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0e02df4a36424885a110fe6e6d2b812f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":54,
                                  "y":47},
                                "size":{
                                  "width":296,
                                  "height":283}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u31.png"}},
{
                          "id":"130e7a5c281f44569ad22a2b68cf297d",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":410,
                              "y":300},
                            "size":{
                              "width":109,
                              "height":160}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f1a46c4200da44c29a170bdb308ef400",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":410,
                                  "y":300},
                                "size":{
                                  "width":109,
                                  "height":160}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u33.png"}}]},
{
                      "id":"97dd0e07006242279ed58ae5bdfc4c48",
                      "label":"历史停车",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"11f7cc2d20144602a9119771583ac6bb",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":55,
                              "y":130},
                            "size":{
                              "width":481,
                              "height":317}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3b5e1471a02945cdbc823c7690083af0",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":55,
                                  "y":130},
                                "size":{
                                  "width":481,
                                  "height":317}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u35.png"}},
{
                          "id":"ebb9b36144f1454eb774c92cd9b91e3b",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":426.000030517578,
                              "y":60},
                            "size":{
                              "width":134,
                              "height":31}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b7efd8bb4a754eaabde4dd470877efbb",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":426.000030517578,
                                  "y":60},
                                "size":{
                                  "width":134,
                                  "height":31}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u37.png"}},
{
                          "id":"34a502927b094e689e795ac8ee9dc621",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "mouseOver":{
                                "outerShadow":{
                                  "on":true,
                                  "offsetX":0,
                                  "offsetY":0,
                                  "blurRadius":10,
                                  "color":{
                                    "r":0,
                                    "g":0,
                                    "b":0,
                                    "a":0.349019607843137}}}},
                            "opacity":"0",
                            "location":{
                              "x":267,
                              "y":285},
                            "size":{
                              "width":36,
                              "height":36}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"644241f974624100aacac7b59cc17098",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "stateStyles":{
                                  "mouseOver":{
                                    "outerShadow":{
                                      "on":true,
                                      "offsetX":0,
                                      "offsetY":0,
                                      "blurRadius":10,
                                      "color":{
                                        "r":0,
                                        "g":0,
                                        "b":0,
                                        "a":0.349019607843137}}}},
                                "opacity":"0",
                                "location":{
                                  "x":267,
                                  "y":285},
                                "size":{
                                  "width":36,
                                  "height":36}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"设置 xq to State1 淡入淡出 in 500ms 显示隐藏",
                                      "panelsToStates":[{
                                          "panelPath":["a2610c4051044698a54f5b6f42733cbf"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":true,
                                            "options":{
                                              "animateIn":{
                                                "easing":"fade",
                                                "duration":500},
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"resources/images/transparent.gif",
                            "mouseOver~":"resources/images/transparent.gif"}},
{
                          "id":"a2610c4051044698a54f5b6f42733cbf",
                          "label":"xq",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"dynamicPanel",
                          "styleType":"dynamicPanel",
                          "visible":false,
                          "style":{
                            "location":{
                              "x":151.5,
                              "y":159},
                            "size":{
                              "width":267,
                              "height":111},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onDrag":{
                              "description":"OnDrag",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"moveWidget",
                                      "description":"移动 123 y 轴拖动",
                                      "objectsToMoves":[{
                                          "objectPath":["d457a899421244838421246a5379445a"],
                                          "moveInfo":{
                                            "moveType":"dragY",
                                            "xValue":{
                                              "exprType":"stringLiteral",
                                              "value":"0",
                                              "stos":[]},
                                            "yValue":{
                                              "exprType":"stringLiteral",
                                              "value":"0",
                                              "stos":[]},
                                            "options":{
}}}]}]}]}},
                          "scrollbars":"none",
                          "fitToContent":false,
                          "propagate":false,
                          "diagrams":[{
                              "id":"3b859367653b41f6a5ede57bc1679c6f",
                              "label":"State1",
                              "type":"Axure:PanelDiagram",
                              "objects":[{
                                  "id":"f7f11cc2e3b94232944f9310d27cffe5",
                                  "label":"",
                                  "parentDynamicPanel":"a2610c4051044698a54f5b6f42733cbf",
                                  "type":"imageBox",
                                  "styleType":"imageBox",
                                  "visible":true,
                                  "style":{
                                    "size":{
                                      "width":267,
                                      "height":111}},
                                  "adaptiveStyles":{
},
                                  "objects":[{
                                      "id":"a9bd1d9752d544558d43ac721500673a",
                                      "label":"",
                                      "isContained":true,
                                      "parentDynamicPanel":"a2610c4051044698a54f5b6f42733cbf",
                                      "type":"richTextPanel",
                                      "styleType":"paragraph",
                                      "visible":true,
                                      "style":{
                                        "size":{
                                          "width":267,
                                          "height":111}},
                                      "adaptiveStyles":{
}}],
                                  "images":{
                                    "normal~":"images/页面_2/u42.png"}},
{
                                  "id":"d457a899421244838421246a5379445a",
                                  "label":"123",
                                  "parentDynamicPanel":"a2610c4051044698a54f5b6f42733cbf",
                                  "type":"imageBox",
                                  "styleType":"imageBox",
                                  "visible":true,
                                  "style":{
                                    "size":{
                                      "width":267,
                                      "height":250}},
                                  "adaptiveStyles":{
},
                                  "objects":[{
                                      "id":"fded2c80028640468511be39a4b35e95",
                                      "label":"",
                                      "isContained":true,
                                      "parentDynamicPanel":"a2610c4051044698a54f5b6f42733cbf",
                                      "type":"richTextPanel",
                                      "styleType":"paragraph",
                                      "visible":true,
                                      "style":{
                                        "size":{
                                          "width":267,
                                          "height":250}},
                                      "adaptiveStyles":{
}}],
                                  "images":{
                                    "normal~":"images/页面_2/123_u44.png"}}]}]}]},
{
                      "id":"1fe64049a4bd42ee96e08005e7cca08e",
                      "label":"我的分享",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"81f0e2ebbd3d40c1bed226b2a4783b3e",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":384},
                            "size":{
                              "width":594,
                              "height":66}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a22878ca6c71422499db599b38a9b48a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":384},
                                "size":{
                                  "width":594,
                                  "height":66}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u46.png"}},
{
                          "id":"84b61910ff8f43a19659be7d20f15e1e",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":171,
                              "y":133},
                            "size":{
                              "width":252,
                              "height":284}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"12545ce5cdc94c869b36d6235be8993a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":171,
                                  "y":133},
                                "size":{
                                  "width":252,
                                  "height":284}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u48.png"}},
{
                          "id":"1542ceb2c1444f2db3d1d4290fba2a10",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "fontName":"'Verdana Negreta', 'Verdana'",
                            "location":{
                              "x":251,
                              "y":62},
                            "size":{
                              "width":92,
                              "height":38}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a3c5a9e1608f4f079cab31e0ac049afd",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Verdana Negreta', 'Verdana'",
                                "location":{
                                  "x":251,
                                  "y":62},
                                "size":{
                                  "width":92,
                                  "height":38}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"ccf4268687b344ed848b72190d3cb1e0",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":39,
                              "y":136},
                            "size":{
                              "width":91,
                              "height":284}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"aef1e1603208431891cb615fa4f0a5c9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":39,
                                  "y":136},
                                "size":{
                                  "width":91,
                                  "height":284}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u52.png"}},
{
                          "id":"d0244583ed70414b9739d65f925b6bcb",
                          "label":"",
                          "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":470,
                              "y":130},
                            "size":{
                              "width":90,
                              "height":284}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"15747149d0bb4e20b6a2a0e43541a922",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"179d3cd6031a4c66a51b271abde3fbef",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":470,
                                  "y":130},
                                "size":{
                                  "width":90,
                                  "height":284}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/页面_2/u54.png"}}]}]},
{
                  "id":"49ab97c0d2394d41b40156e46c455a1f",
                  "label":"",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":616},
                    "size":{
                      "width":454,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 xx to 停车统计 向左滑动 out 500ms 向右滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["179d3cd6031a4c66a51b271abde3fbef"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideRight",
                                        "duration":500},
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 zhe",
                              "objectsToFades":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 zhe 到 (70,608) 弹跳 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"70",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"608",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeOutBounce",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"2cd0a28d21ed48e4bac93a5b5f4a7457",
                  "label":"",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":706},
                    "size":{
                      "width":454,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 xx to 我的积分 向左滑动 out 500ms 向右滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["179d3cd6031a4c66a51b271abde3fbef"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideRight",
                                        "duration":500},
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 zhe",
                              "objectsToFades":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 zhe 到 (70,698) 弹跳 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"70",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"698",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeOutBounce",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"126fc56af787413cbb5c08f7c3c751f6",
                  "label":"",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":796},
                    "size":{
                      "width":454,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 xx to 历史停车 向左滑动 out 500ms 向右滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["179d3cd6031a4c66a51b271abde3fbef"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideRight",
                                        "duration":500},
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 zhe",
                              "objectsToFades":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 zhe 到 (70,788) 弹跳 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"70",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"788",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeOutBounce",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"cd7da141d8e14402b80dbab33adb3cce",
                  "label":"",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":886},
                    "size":{
                      "width":454,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 xx to 我的分享 向左滑动 out 500ms 向右滑动 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["179d3cd6031a4c66a51b271abde3fbef"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":5,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideLeft",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"slideRight",
                                        "duration":500},
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 zhe",
                              "objectsToFades":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 zhe 到 (70,878) 弹跳 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["34685f437bb949abbff1217f47286a37"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"70",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"878",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeOutBounce",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"454e907c129d470388e551245deb647b",
                  "label":"",
                  "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseOver":{
                        "outerShadow":{
                          "on":true,
                          "offsetX":0,
                          "offsetY":0,
                          "blurRadius":25,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "mouseDown":{
                        "outerShadow":{
                          "on":true,
                          "offsetX":0,
                          "offsetY":0,
                          "blurRadius":15,
                          "color":{
                            "r":255,
                            "g":255,
                            "b":0,
                            "a":0.349019607843137}}}},
                    "location":{
                      "x":42,
                      "y":475},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fdb6ce83508f4ca7a4c876d4177fa35a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b33baae50e56473a89a01bdd62c0080a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseOver":{
                            "outerShadow":{
                              "on":true,
                              "offsetX":0,
                              "offsetY":0,
                              "blurRadius":25,
                              "color":{
                                "r":0,
                                "g":0,
                                "b":0,
                                "a":0.349019607843137}}},
                          "mouseDown":{
                            "outerShadow":{
                              "on":true,
                              "offsetX":0,
                              "offsetY":0,
                              "blurRadius":15,
                              "color":{
                                "r":255,
                                "g":255,
                                "b":0,
                                "a":0.349019607843137}}}},
                        "location":{
                          "x":42,
                          "y":475},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 页面 1",
                              "target":{
                                "targetType":"page",
                                "url":"页面_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/页面_1/u3.png",
                    "mouseOver~":"images/页面_2/u60_mouseOver.png",
                    "mouseDown~":"images/页面_1/u3_mouseDown.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "b33baae50e56473a89a01bdd62c0080a":{
      "scriptId":"u0"},
    "da1484641abb4ad0abaa03daf186f3f1":{
      "scriptId":"u1"},
    "5e98fe0c636841d590d5b1da51b78323":{
      "scriptId":"u2"},
    "34685f437bb949abbff1217f47286a37":{
      "scriptId":"u3"},
    "6c4ee13a5661418780ebafd9a3bf60e3":{
      "scriptId":"u4"},
    "733c7d418bf74984b079d9c434efe369":{
      "scriptId":"u5"},
    "d731c00f63ce470facd4ded43b6e87fa":{
      "scriptId":"u6"},
    "a99e97b7a8de476abb7607a1894c6101":{
      "scriptId":"u7"},
    "179d3cd6031a4c66a51b271abde3fbef":{
      "scriptId":"u8"},
    "18ca3b3e2cac45e5920c2702db6c679d":{
      "scriptId":"u9"},
    "33ca4150375144d193edeac5d7621bcd":{
      "scriptId":"u10"},
    "c2cf086899c148f892f0c10b3f8b58a9":{
      "scriptId":"u11"},
    "20045bee4d84498aab1c50946fd500b1":{
      "scriptId":"u12"},
    "434bbec138ca44ed831f356a517d9871":{
      "scriptId":"u13"},
    "3ef7e9f502564813b4c3523c58562632":{
      "scriptId":"u14"},
    "4a69b97f8cb74b5eb4617cb93c7a9a91":{
      "scriptId":"u15"},
    "9f28af26d9ae4a958e26cb6b6e2b0aa2":{
      "scriptId":"u16"},
    "1cb63ceb852e42ce8f816d6d8aeb5975":{
      "scriptId":"u17"},
    "566793a500b54b36be934c1009b3741c":{
      "scriptId":"u18"},
    "45ac988c29aa4356b629ce15c034d409":{
      "scriptId":"u19"},
    "5f022ce6becb4893aa4da13325273412":{
      "scriptId":"u20"},
    "cd35f46d743e4ee38511202a590cbfc6":{
      "scriptId":"u21"},
    "2791cf8fcde8401e8629bdbf25bc09ed":{
      "scriptId":"u22"},
    "b208e363ce2549f495891bada0114b71":{
      "scriptId":"u23"},
    "d35976a9270a4a88bcf7e29ad32e04be":{
      "scriptId":"u24"},
    "203b376dc69f4c289d11ca35788d42e8":{
      "scriptId":"u25"},
    "39d0d6fac8a84b6fa523922cdccc0255":{
      "scriptId":"u26"},
    "e0aee75a477d4e41bcc0619617f9a938":{
      "scriptId":"u27"},
    "3cfd209d2a3744399c617bed012828f5":{
      "scriptId":"u28"},
    "640ad4ef83434c4d99ae88e7cba1d702":{
      "scriptId":"u29"},
    "f3a5bc8a67bb4837ae43a193b6e37146":{
      "scriptId":"u30"},
    "bacb11d957d642478f9709412c62e0c5":{
      "scriptId":"u31"},
    "0e02df4a36424885a110fe6e6d2b812f":{
      "scriptId":"u32"},
    "130e7a5c281f44569ad22a2b68cf297d":{
      "scriptId":"u33"},
    "f1a46c4200da44c29a170bdb308ef400":{
      "scriptId":"u34"},
    "11f7cc2d20144602a9119771583ac6bb":{
      "scriptId":"u35"},
    "3b5e1471a02945cdbc823c7690083af0":{
      "scriptId":"u36"},
    "ebb9b36144f1454eb774c92cd9b91e3b":{
      "scriptId":"u37"},
    "b7efd8bb4a754eaabde4dd470877efbb":{
      "scriptId":"u38"},
    "34a502927b094e689e795ac8ee9dc621":{
      "scriptId":"u39"},
    "644241f974624100aacac7b59cc17098":{
      "scriptId":"u40"},
    "a2610c4051044698a54f5b6f42733cbf":{
      "scriptId":"u41"},
    "f7f11cc2e3b94232944f9310d27cffe5":{
      "scriptId":"u42"},
    "a9bd1d9752d544558d43ac721500673a":{
      "scriptId":"u43"},
    "d457a899421244838421246a5379445a":{
      "scriptId":"u44"},
    "fded2c80028640468511be39a4b35e95":{
      "scriptId":"u45"},
    "81f0e2ebbd3d40c1bed226b2a4783b3e":{
      "scriptId":"u46"},
    "a22878ca6c71422499db599b38a9b48a":{
      "scriptId":"u47"},
    "84b61910ff8f43a19659be7d20f15e1e":{
      "scriptId":"u48"},
    "12545ce5cdc94c869b36d6235be8993a":{
      "scriptId":"u49"},
    "1542ceb2c1444f2db3d1d4290fba2a10":{
      "scriptId":"u50"},
    "a3c5a9e1608f4f079cab31e0ac049afd":{
      "scriptId":"u51"},
    "ccf4268687b344ed848b72190d3cb1e0":{
      "scriptId":"u52"},
    "aef1e1603208431891cb615fa4f0a5c9":{
      "scriptId":"u53"},
    "d0244583ed70414b9739d65f925b6bcb":{
      "scriptId":"u54"},
    "15747149d0bb4e20b6a2a0e43541a922":{
      "scriptId":"u55"},
    "49ab97c0d2394d41b40156e46c455a1f":{
      "scriptId":"u56"},
    "2cd0a28d21ed48e4bac93a5b5f4a7457":{
      "scriptId":"u57"},
    "126fc56af787413cbb5c08f7c3c751f6":{
      "scriptId":"u58"},
    "cd7da141d8e14402b80dbab33adb3cce":{
      "scriptId":"u59"},
    "454e907c129d470388e551245deb647b":{
      "scriptId":"u60"},
    "fdb6ce83508f4ca7a4c876d4177fa35a":{
      "scriptId":"u61"}}});